name: 3DS Build

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  DevKitPro:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Install build requirements
        run: |
          apt update
          apt install ninja-build 
      - name: Build the homebrew application
        run: make      